// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unievent.Infra.Data;

#nullable disable

namespace Unievent.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unievent.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveConfirmacaoEmail")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoParticipante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChaveConfirmacaoEmail")
                        .IsUnique()
                        .HasFilter("[ChaveConfirmacaoEmail] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCertifcado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Certificado");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FimInscricoes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InicioInscricoes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicoPermitido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaioCheckInMetros")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsavelEventoId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ToleranciaCheckInMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelEventoId");

                    b.HasIndex("InstituicaoId", "Categoria");

                    b.HasIndex("InstituicaoId", "DataEvento");

                    b.HasIndex("Visibilidade", "PublicoPermitido");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Instituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NomeAbreviado")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Site")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[Codigo] IS NOT NULL");

                    b.ToTable("Instituicao");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.NotificacaoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Enviada")
                        .HasColumnType("boolean");

                    b.Property<string>("Erro")
                        .HasColumnType("text");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("AlunoId", "EventoId", "Tipo")
                        .IsUnique();

                    b.ToTable("NotificacaoEvento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Participacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<bool>("CertificadoEmitido")
                        .HasColumnType("boolean");

                    b.Property<bool>("CertificadoEnviadoPorEmail")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("CertificadoPdf")
                        .HasColumnType("bytea");

                    b.Property<string>("CodigoIngresso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoValidacao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEnvioCertificadoEmail")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataGeracaoCertificado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinatarioCertificadoEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<double?>("DistanciaCheckInMetros")
                        .HasColumnType("double precision");

                    b.Property<string>("ErroEnvioCertificadoEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivoCertificado")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("OperadorCheckInId")
                        .HasColumnType("integer");

                    b.Property<double?>("PrecisaoLocalizacaoMetros")
                        .HasColumnType("double precision");

                    b.Property<bool>("PresencaConfirmada")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessamentoCertificadoAteUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessamentoCertificadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProximaTentativaCertificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusEnvioCertificado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StatusInscricao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Ativa");

                    b.Property<int>("TentativasEnvioCertificado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIngresso")
                        .IsUnique();

                    b.HasIndex("EventoId");

                    b.HasIndex("AlunoId", "EventoId")
                        .IsUnique();

                    b.HasIndex("StatusEnvioCertificado", "ProximaTentativaCertificadoUtc");

                    b.ToTable("Participacao");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.PreferenciaNotificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertasCertificados")
                        .HasColumnType("boolean");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categorias")
                        .HasColumnType("text");

                    b.Property<double?>("LatitudeAproximada")
                        .HasColumnType("double precision");

                    b.Property<bool>("LembretesEventos")
                        .HasColumnType("boolean");

                    b.Property<double?>("LongitudeAproximada")
                        .HasColumnType("double precision");

                    b.Property<int>("RaioKm")
                        .HasColumnType("integer");

                    b.Property<bool>("Recomendacoes")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsarLocalizacao")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("PreferenciaNotificacao");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.ResponsavelEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("ResponsavelEvento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.UsuarioSecretaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TentativasLogin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.HasIndex("EmailUsuario")
                        .IsUnique();

                    b.HasIndex("InstituicaoId");

                    b.ToTable("UsuarioSecretaria");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.UsuarioUnievent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TentativasLogin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.HasIndex("EmailUsuario")
                        .IsUnique();

                    b.ToTable("UsuarioUnievent");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Evento", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Unievent.Domain.Entities.ResponsavelEvento", "ResponsavelEvento")
                        .WithMany()
                        .HasForeignKey("ResponsavelEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("ResponsavelEvento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.NotificacaoEvento", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unievent.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.Participacao", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unievent.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.PreferenciaNotificacao", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Aluno", "Aluno")
                        .WithOne()
                        .HasForeignKey("Unievent.Domain.Entities.PreferenciaNotificacao", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.ResponsavelEvento", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("Unievent.Domain.Entities.UsuarioSecretaria", b =>
                {
                    b.HasOne("Unievent.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instituicao");
                });
#pragma warning restore 612, 618
        }
    }
}
